#ifndef INSTRUCTIONS_H
#define INSTRUCTIONS_H
void add( short& rd,  short rs,  short rt);
void addi( short rt,  short rs,  short imm);
void addiu( short rt,  short rs,  short imm);
void addu( short& rd,  short rs,  short rt);
void andd( short& rd,  short rs,  short rt);
void andi( short rt,  short rs,  short imm);
void beq( short rs,  short rt,  short imm);
void bgez( short rs,  short imm);
void bgezal( short rs,  short imm);
void bgtz( short rs,  short imm);
void blez( short rs,  short imm);
void bltz( short rs,  short imm);
void bltzal( short rs,  short imm);
void bne( short rs,  short rt,  short imm);
void div( short rs,  short rt);
void divu( short rs,  short rt);
void j( short address);
void jalr( short& rd,  short rs);
void jal( short address);
void jr( short rs);
void syscall();
void lb( short rt,  short rs,  short imm);
void lbu( short rt,  short rs,  short imm);
void lh( short rt,  short rs,  short imm);
void lhu( short rt,  short rs,  short imm);
void lui( short rt,  short imm);
void lw( short rt,  short rs,  short imm);
void lwl( short rt,  short rs,  short imm);
void lwr( short rt,  short rs,  short imm);
void mfhi( short& rd);
void mflo( short& rd);
void mthi( short rs);
void mtlo( short rs);
void mult(signed short rs, signed short rt);
void multu( short rs,  short rt);
void orr( short& rd,  short rs,  short rt);
void ori( short rt,  short rs,  short imm);
void sb( short rt,  short rs,  short imm);
void sh( short rt,  short rs,  short imm);
void sll( short& rd,  short rt,  short shamt);
void sllv( short& rd,  short rt,  short rs);
void slt( short& rd,  short rs,  short rt);
void slti( short rt,  short rs,  short imm);       
void sltiu( short rt,  short rs,  short imm);
void sltu( short& rd,  short rs,  short rt);
void sra( short& rd,  short rt,  short shamt);
void srav( short& rd,  short rt,  short rs);
void srl( short& rd,  short rt,  short shamt);
void srlv( short& rd,  short rt,  short rs);
void sub( short& rd,  short rs,  short rt);
void subu( short& rd,  short rs,  short rt);
void sw( short rt,  short rs,  short imm);
void xorr( short& rd,  short rs,  short rt);
void xori( short rt,  short rs,  short imm);
void insexecute(int instype,  short decoded1,  short decoded2,  long decoded3);

#endif